# Generated by Django 3.0.7 on 2022-10-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_studentresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='subject_assignment_marks',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject_first_test',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject_second_test',
            field=models.FloatField(default=0, null=True),
        ),
    ]
